export const gearTypes = {
  GET_PRODUCT_INFO_REQUEST: 'PRODUCT_INFO_REQUEST',
  GET_PRODUCT_INFO_SUCCESS: 'PRODUCT_INFO_SUCCESS',
  GET_PRODUCT_INFO_FAILURE: 'PRODUCT_INFO_FAILURE',
  GET_PRODUCT_OWNERS_REQUEST: 'PRODUCT_OWNERS_REQUEST',
  GET_PRODUCT_OWNERS_SUCCESS: 'PRODUCT_OWNERS_SUCCESS',
  GET_PRODUCT_OWNERS_FAILURE: 'PRODUCT_OWNERS_FAILURE'
};