export const searchTypes = {
  GET_SEARCH_RESULTS_REQUEST: 'GET_SEARCH_RESULTS_REQUEST',
  GET_SEARCH_RESULTS_SUCCESS: 'GET_SEARCH_RESULTS_SUCCESS',
  GET_SEARCH_RESULTS_FAILURE: 'GET_SEARCH_RESULTS_FAILURE',

  GET_SEARCHPROJECT_RESULTS_REQUEST: 'GET_SEARCHPROJECT_RESULTS_REQUEST',
  GET_SEARCHPROJECT_RESULTS_SUCCESS: 'GET_SEARCHPROJECT_RESULTS_SUCCESS',
  GET_SEARCHPROJECT_RESULTS_FAILURE: 'GET_SEARCHPROJECT_RESULTS_FAILURE',

  SEARCH_USERS_REQUEST: 'SEARCH_USERS_REQUEST',
  SEARCH_USERS_SUCCESS: 'SEARCH_USERS_SUCCESS',
  SEARCH_USERS_FAILURE: 'SEARCH_USERS_FAILURE',

  SEARCH_PROJECTS_REQUEST: 'SEARCH_PROJECTS_REQUEST',
  SEARCH_PROJECTS_SUCCESS: 'SEARCH_PROJECTS_SUCCESS',
  SEARCH_PROJECTS_FAILURE: 'SEARCH_PROJECTS_FAILURE',
  RESET_SEARCH_PROJECTS: 'RESET_SEARCH_PROJECTS',

  SEARCH_GEAR_REQUEST: 'SEARCH_GEAR_REQUEST',
  SEARCH_GEAR_SUCCESS: 'SEARCH_GEAR_SUCCESS',
  SEARCH_GEAR_FAILURE: 'SEARCH_GEAR_FAILURE',

  SEARCH_BRANDS_REQUEST: 'SEARCH_BRANDS_REQUEST',
  SEARCH_BRANDS_SUCCESS: 'SEARCH_BRANDS_SUCCESS',
  SEARCH_BRANDS_FAILURE: 'SEARCH_BRANDS_FAILURE',

  GET_SUGGESTEDUSERS_REQUEST: 'GET_SUGGESTEDUSERS_REQUEST',
  GET_SUGGESTEDUSERS_SUCCESS: 'GET_SUGGESTEDUSERS_SUCCESS',
  GET_SUGGESTEDUSERS_FAILURE: 'GET_SUGGESTEDUSERS_FAILURE',

  GET_SUGGESTED_FEATURED_USERS_REQUEST: 'GET_SUGGESTED_FEATURED_USERS_REQUEST',
  GET_SUGGESTED_FEATURED_USERS_SUCCESS: 'GET_SUGGESTED_FEATURED_USERS_SUCCESS',
  GET_SUGGESTED_FEATURED_USERS_FAILURE: 'GET_SUGGESTED_FEATURED_USERS_FAILURE',

  GET_SUGGESTED_NEW_USERS_REQUEST: 'GET_SUGGESTED_NEW_USERS_REQUEST',
  GET_SUGGESTED_NEW_USERS_SUCCESS: 'GET_SUGGESTED_NEW_USERS_SUCCESS',
  GET_SUGGESTED_NEW_USERS_FAILURE: 'GET_SUGGESTED_NEW_USERS_FAILURE',

  GET_FEATURED_PROJECTS_REQUEST: 'GET_FEATURED_PROJECTS_REQUEST',
  GET_FEATURED_PROJECTS_SUCCESS: 'GET_FEATURED_PROJECTS_SUCCESS',
  GET_FEATURED_PROJECTS_FAILURE: 'GET_FEATURED_PROJECTS_FAILURE',

  GET_USERLASTSEARCHES_REQUEST: 'GET_USERLASTSEARCHES_REQUEST',
  GET_USERLASTSEARCHES_SUCCESS: 'GET_USERLASTSEARCHES_SUCCESS',
  GET_USERLASTSEARCHES_FAILURE: 'GET_USERLASTSEARCHES_FAILURE',
};