export const userTypes = {
  GET_USER_INFO_REQUEST: 'USER_GETALL_REQUEST',
  GET_USER_INFO_SUCCESS: 'USER_GETALL_SUCCESS',
  GET_USER_INFO_FAILURE: 'USER_GETALL_FAILURE',

  GET_USER_GENRES_INFO_REQUEST: 'GET_USER_GENRES_INFO_REQUEST',
  GET_USER_GENRES_INFO_SUCCESS: 'GET_USER_GENRES_INFO_SUCCESS',
  GET_USER_GENRES_INFO_FAILURE: 'GET_USER_GENRES_INFO_FAILURE',

  GET_USER_ROLES_INFO_REQUEST: 'GET_USER_ROLES_INFO_REQUEST',
  GET_USER_ROLES_INFO_SUCCESS: 'GET_USER_ROLES_INFO_SUCCESS',
  GET_USER_ROLES_INFO_FAILURE: 'GET_USER_ROLES_INFO_FAILURE',

  GET_USER_GEAR_REQUEST: 'GET_USER_GEAR_REQUEST',
  GET_USER_GEAR_SUCCESS: 'GET_USER_GEAR_SUCCESS',
  GET_USER_GEAR_FAILURE: 'GET_USER_GEAR_FAILURE',

  GET_USER_GEARSETUPS_REQUEST: 'GET_USER_GEARSETUPS_REQUEST',
  GET_USER_GEARSETUPS_SUCCESS: 'GET_USER_GEARSETUPS_SUCCESS',
  GET_USER_GEARSETUPS_FAILURE: 'GET_USER_GEARSETUPS_FAILURE',

  GET_USER_GEARSETUPITEMS_REQUEST: 'USER_GEARSETUPITEMS_REQUEST',
  GET_USER_GEARSETUPITEMS_SUCCESS: 'USER_GEARSETUPITEMS_SUCCESS',
  GET_USER_GEARSETUPITEMS_FAILURE: 'USER_GEARSETUPITEMS_FAILURE',

  GET_USER_PARTNERS_REQUEST: 'GET_USER_PARTNERS_REQUEST',
  GET_USER_PARTNERS_SUCCESS: 'GET_USER_PARTNERS_SUCCESS',
  GET_USER_PARTNERS_FAILURE: 'GET_USER_PARTNERS_FAILURE',

  GET_USER_AVAILABILITY_ITEMS_REQUEST: 'GET_USER_AVAILABILITY_ITEMS_REQUEST',
  GET_USER_AVAILABILITY_ITEMS_SUCCESS: 'GET_USER_AVAILABILITY_ITEMS_SUCCESS',
  GET_USER_AVAILABILITY_ITEMS_FAILURE: 'GET_USER_AVAILABILITY_ITEMS_FAILURE',

  GET_USER_LAST_CONNECTED_FRIENDS_REQUEST: 'GET_USER_LAST_CONNECTED_FRIENDS_REQUEST',
  GET_USER_LAST_CONNECTED_FRIENDS_SUCCESS: 'GET_USER_LAST_CONNECTED_FRIENDS_SUCCESS',
  GET_USER_LAST_CONNECTED_FRIENDS_FAILURE: 'GET_USER_LAST_CONNECTED_FRIENDS_FAILURE',
};