export const userProjectsTypes = {
  GET_USER_PROJECTS_REQUEST: 'GET_USER_PROJECTS_REQUEST',
  GET_USER_PROJECTS_SUCCESS: 'GET_USER_PROJECTS_SUCCESS',
  GET_USER_PROJECTS_FAILURE: 'GET_USER_PROJECTS_FAILURE',
  GET_USER_PROJECTS_BASIC_INFO_REQUEST: 'GET_USER_PROJECTS_BASIC_INFO_REQUEST',
  GET_USER_PROJECTS_BASIC_INFO_SUCCESS: 'GET_USER_PROJECTS_BASIC_INFO_SUCCESS',
  GET_USER_PROJECTS_BASIC_INFO_FAILURE: 'GET_USER_PROJECTS_BASIC_INFO_FAILURE',
};